### ISSUE TITLE
SidePanel.removePaneByID fails 

### ISSUE THREAD

**Issue by embracethemirth** [symbioquine/ol-side-panel#1]
Kia ora symbioquine,

Nice work! I have built out a class that extends sidepanel and when I call the method:
`this.removePaneByID()`
despite giving the appropriate paneId, I've noticed that I get an error: 
`Uncaught TypeError: Node.removeChild: Argument 1 does not implement interface Node.`
the function itself is expecting an ID to find the element that represents the pane but gets passed an object instead.

Changing line 70 of src/SidePanel.js 
from:
`tabList.removeChild(evt.element.tabRef_);`
to:
`tabList.removeChild(evt.element.tabRef_.element_);`
fixes the issue.

**Comment by symbioquine** [comment]
Good catch @embracethemirth!
