### ISSUE TITLE
How should i place the side-panel on the right side inspite of left side 

### ISSUE THREAD

**Issue by ramanamuttana** [symbioquine/ol-side-panel#2]
is there a way to adjust the side -panel on the right side inspite of left side , i tried changing css , but it did not work

**Comment by symbioquine** [comment]
That is not currently supported.

However, it should be possible by providing (with [higher specificity](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity)) your own CSS (see [SidePanel.css](https://github.com/symbioquine/ol-side-panel/blob/main/src/SidePanel.css)) for the panel/widgets/etc.

e.g. you'd need to add your own class to your parent map div (or something like that), then create your own style rules that have higher specificity;

*Untested:*

```patch
 ...
 
 .my-custom-class .ol-side-panel .ol-side-panel-tabs {
-   left: 0;
+   right: 0;
 }
 
 ...
```

...and do something similar for all the styles in there.
